// PRICES
export const GET_BITCOIN_PRICE = "GET_BITCOIN_PRICE";
export const GET_BITCOIN_PRICE_SUCCESS = "GET_BITCOIN_PRICE_SUCCESS";
export const GET_ETHEREUM_PRICE = "GET_ETHEREUM_PRICE";
export const GET_ETHEREUM_PRICE_SUCCESS = "GET_ETHEREUM_PRICE_SUCCESS";
export const GET_LITCOIN_PRICE = "GET_LITCOIN_PRICE";
export const GET_LITCOIN_PRICE_SUCCESS = "GET_LITCOIN_PRICE_SUCCESS";


// GRAPH
export const GET_BITCOIN_MARKET_MONTH = "GET_BITCOIN_MARKET_MONTH";
export const GET_BITCOIN_MARKET_SIXMONTH = "GET_BITCOIN_MARKET_SIXMONTH";
export const GET_BITCOIN_MARKET_YEAR = "GET_BITCOIN_MARKET_YEAR";
export const GET_BITCOIN_MARKET_ALL = "GET_BITCOIN_MARKET_ALL";